# generated by cabal-rpm-0.13
# https://fedoraproject.org/wiki/Packaging:Haskell

# nothing to see here
%global debug_package %{nil}

%global pkg_name ShellCheck
%global pkgver %{pkg_name}-%{version}

%global ghc_without_dynamic 1

Name:           %{pkg_name}
Version:        0.6.0
Release:        1%{?dist}
Summary:        Shell script analysis tool

License:        GPLv3+
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
%if %{defined fedora}
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-regex-tdfa-devel
# End cabal-rpm deps
%else
BuildRequires:  ghc-libraries
%endif
BuildRequires:  cabal-install >= 1.18

%description
The goals of ShellCheck are:

* To point out and clarify typical beginner's syntax issues, that causes a
shell to give cryptic error messages.

* To point out and clarify typical intermediate level semantic problems, that
causes a shell to behave strangely and counter-intuitively.

* To point out subtle caveats, corner cases and pitfalls, that may cause an
advanced user's otherwise working script to fail under future circumstances.


%prep
%setup -q
# End cabal-rpm setup


%build
%global cabal cabal
%cabal update
%cabal sandbox init
%cabal install


%install
install -Dp .cabal-sandbox/bin/shellcheck %{buildroot}%{_bindir}/shellcheck

install -Dpm 0644 shellcheck.1 %{buildroot}%{_mandir}/man1/shellcheck.1


%files
# Begin cabal-rpm files:
%license LICENSE
%doc README.md
%{_bindir}/shellcheck
# End cabal-rpm files
%{_mandir}/man1/shellcheck.1*



%changelog
* Wed Jan  9 2019 Jens Petersen <petersen@redhat.com> - 0.6.0-1
- update to 0.6.0

* Fri Mar  2 2018 Jens Petersen <petersen@redhat.com> - 0.4.7-1
- package for el7
